### ISSUE TITLE
ToUpper 

### ISSUE THREAD

**Issue by 9hk** [benhoyt/io-performance#1]
https://github.com/benhoyt/io-performance/blob/a0ecd220b56191c03d7d625af24f326bd9a2eb2a/simple.go#L25

FYI, when doing case folding, its better to use ToUpper:

https://stackoverflow.com/a/65433126

I don't think this changes the speed, but it will change the accuracy. ToLower is good for situations where you know one "side" will be a certain case (user input). In that case, since you know one side will be lowercase already, you don't need to lowercase it, you can just lowercase the other side, saving time at the cost of some accuracy. But in this case, we are comparing the file against itself, so you cant really make any assumptions. The whole file could be uppercase to start.

**Comment by benhoyt** [comment]
Thanks for the note. I guess I just prefer lowercase output for these things, so choosing that is mostly out of habit. :-) However, in this case it doesn't really matter as it's not the point of the exercise, so I'm going to leave this as is.
