### ISSUE TITLE
Go: Use bufio package

### ISSUE THREAD

**Issue by oliverpool** [benhoyt/io-performance#2]
Hi,
did you try using the bufio package from the standard library?

The example Scanner (words) looks like a perfect fit:
https://pkg.go.dev/bufio#example-Scanner-Words

**Comment by benhoyt** [comment]
Yeah, if you look at my more in-depth analysis of the count-words problem I use `bufio.Scanner` with `ScanWords` for the "simple" Go solution: https://benhoyt.com/writings/count-words/#go

However, for this article I wanted to easily separate out read time from processing time, which is harder with `bufio`.

**Comment by oliverpool** [comment]
My bad, I only looked at the code on the git repo, where it isn’t used.

**Comment by oliverpool** [comment]
However I think it will make the optimized version much more readable
